apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ucsg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-ucsg@sha256:6724d44cd649ca65831b27d2832ae8f4a5d6bb1de4225fa2f01a3faf040cf091
        name: my-nodejs
        resources: {}
status: {}
